[package]
name = "third-wheel"
version = "0.3.3"
authors = ["Chris Campbell <campbellC@user.noreply.github.com>"]
edition = "2018"
readme = "README.md"
categories = ["network-programming", "command-line-utilities"]
keywords = ["mitmproxy", "man-in-the-middle", "penetration"]
description = "third-wheel is a TLS man-in-the-middle proxy written in rust, with the aim of being lightweight and fast. It is currently in pre-alpha stage."
repository = "https://www.github.com/campbellC/third-wheel"
license = "MIT"

[features]
binaries = ['argh', 'simple_logger']
har-capture = ['binaries', 'har', 'cookie']


[dependencies]
openssl = "0.10.30"
httparse = "1.3.4"
bytes = "0.5.4"
http = "0.2.1"
futures = "0.3.5"
time = "0.1.42"
native-tls = "^0.2"
tokio-native-tls = "0.1.0"
lazy_static = "1.4.0"
log = "^0.4"
async-trait = "^0.1"
argh = {version="^0.1", optional = true}
simple_logger = {version="^1", optional=true}
har = {version = "^0.5", optional=true}
cookie = {version = "^0.14", optional=true}

[dependencies.tokio]
version = "0.2.21"
features = ["macros", "rt-threaded", "tcp", "io-util", "tcp", "dns", "time"]

[dependencies.tokio-util]
version = "0.3.1"
features = ["codec"]

[[bin]]
name = "sign_cert_for_site"
required-features = ["binaries"]

[[bin]]
name = "trivial_mitm"
required-features = ["binaries"]

[[bin]]
name = "har-capture"
required-features = ["har-capture"]
